services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: zurluser
      POSTGRES_PASSWORD: zurlpass
      POSTGRES_DB: zurl
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
